[package]
name = "gas_tests"
version = "0.0.0"
edition = "2024"
publish = false

[lib]
path = "src/gas_tests.rs"

[dependencies.multiversx-sc]
version = "0.65.1"
path = "../../../framework/base"

[dev-dependencies.multiversx-sc-scenario]
version = "0.65.1"
path = "../../../framework/scenario"

[dependencies.multiversx-chain-vm-wasmer-prod]
path = "../../../chain/wasmer-prod"
optional = true

[features]
wasmer-prod = ["multiversx-chain-vm-wasmer-prod"]
wasmer-experimental = ["multiversx-sc-scenario/wasmer-experimental"]

[workspace]
members = ["."]

[patch.crates-io]
multiversx-chain-vm-executor = { git = "https://github.com/Shanmugavardhan/mx-vm-executor-rs", rev = "69167eb16e3ed3874e77b48df29daa9acb5c8b25"}
multiversx-chain-vm-executor-wasmer-experimental = { git = "https://github.com/Shanmugavardhan/mx-vm-executor-rs", rev = "69167eb16e3ed3874e77b48df29daa9acb5c8b25"}

